apiVersion: apps/v1
kind: Deployment
metadata:
  name: redefinee-website
  labels:
    app: redefinee-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redefinee-website
  template:
    metadata:
      labels:
        app: redefinee-website
    spec:
      containers:
      - name: redefinee-website
        image: levin16robert/redefinee-website-pipeline:1.0.0-39
        ports:
        - containerPort: 3000
